delete tb_tableinfo t where t.file_name like '%PROJECT_LOAN_GZH%';
delete tb_tableinfo t where t.file_name like '%SYN_GZH%';

delete tb_tableinfo t where t.file_name like '%PROJECT_LOAN_SZN%';
delete tb_tableinfo t where t.file_name like '%SYN_SZN%';

delete tb_tableinfo t where t.file_name like '%PROJECT_LOAN_BJG%';
delete tb_tableinfo t where t.file_name like '%SYN_BJG%';

-----------PROJECT_LOAN_GZH_YYYYMMDD(项目贷款模板)。
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'COUN_CODE', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'GROU_MEME', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'BRAN_CODE', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'CUST_SERI', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'LIMI_GROUP', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'LIMI_TYPE', null, null, null, null, 6, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'LIMI_LINE', null, null, null, null, 7, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'PROJ_NAME', null, null, null, null, 8, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'PROJ_TYPE', null, null, null, null, 9, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'SYN_LOAN', null, null, null, null, 10, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'TOTA_INVE_CCY', null, null, null, null, 11, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'TOTA_INVE_AMT', null, null, null, null, 12, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'CAP_CCY', null, null, null, null, 13, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'CAP_CCY_AMT', null, null, null, null, 14, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'PROJ_LOAN_CCY', null, null, null, null, 15, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'PROJ_LOAN_AMT', null, null, null, null, 16, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'PROJ_LOAN_B_DATE', null, null, null, null, 17, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'PROJ_LOAN_E_DATE', null, null, null, null, 18, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'APPR_NO', null, null, null, null, 19, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'PROJ_APPR', null, null, null, null, 20, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'PLAN_LICEN_NO', null, null, null, null, 21, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'CON_LAND_LICEN_NO', null, null, null, null, 22, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'EIA_LICEN_NO', null, null, null, null, 23, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'CON_PER_NO', null, null, null, null, 24, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'OTH_PER_LAND', null, null, null, null, 25, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'OTH_PER_NO', null, null, null, null, 26, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'START_DATE', null, null, null, null, 27, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'COMP_TOTA_INVE_CCY', null, null, null, null, 28, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'COMP_TOTA_INVE_AMT', null, null, null, null, 29, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'COMP_CAP_CCY', null, null, null, null, 30, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_GZH', 'E_PROJECT_LOAN', 'COMP_CAP_CCY_AMT', null, null, null, null, 31, null, null, null, null);
commit;

-------------SYN_GZH_YYYYMM(银团贷款模板)
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'XDHTH1', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'XDHTH2', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'XYQSRQ', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'XYZZRQ', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'SQDKZE1', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'SQDKZE2', null, null, null, null, 6, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'ZBXXM', null, null, null, null, 7, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'DLXXM', null, null, null, null, 8, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_GZH', 'E_SYNDICATED_LOAN', 'CDXXM', null, null, null, null, 9, null, null, null, null);
commit;



-----------PROJECT_LOAN_SZN_YYYYMMDD(项目贷款模板)。
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'COUN_CODE', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'GROU_MEME', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'BRAN_CODE', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'CUST_SERI', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'LIMI_GROUP', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'LIMI_TYPE', null, null, null, null, 6, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'LIMI_LINE', null, null, null, null, 7, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'PROJ_NAME', null, null, null, null, 8, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'PROJ_TYPE', null, null, null, null, 9, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'SYN_LOAN', null, null, null, null, 10, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'TOTA_INVE_CCY', null, null, null, null, 11, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'TOTA_INVE_AMT', null, null, null, null, 12, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'CAP_CCY', null, null, null, null, 13, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'CAP_CCY_AMT', null, null, null, null, 14, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'PROJ_LOAN_CCY', null, null, null, null, 15, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'PROJ_LOAN_AMT', null, null, null, null, 16, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'PROJ_LOAN_B_DATE', null, null, null, null, 17, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'PROJ_LOAN_E_DATE', null, null, null, null, 18, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'APPR_NO', null, null, null, null, 19, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'PROJ_APPR', null, null, null, null, 20, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'PLAN_LICEN_NO', null, null, null, null, 21, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'CON_LAND_LICEN_NO', null, null, null, null, 22, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'EIA_LICEN_NO', null, null, null, null, 23, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'CON_PER_NO', null, null, null, null, 24, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'OTH_PER_LAND', null, null, null, null, 25, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'OTH_PER_NO', null, null, null, null, 26, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'START_DATE', null, null, null, null, 27, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'COMP_TOTA_INVE_CCY', null, null, null, null, 28, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'COMP_TOTA_INVE_AMT', null, null, null, null, 29, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'COMP_CAP_CCY', null, null, null, null, 30, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_SZN', 'E_PROJECT_LOAN', 'COMP_CAP_CCY_AMT', null, null, null, null, 31, null, null, null, null);
commit;

-------------SYN_SZN_YYYYMM(银团贷款模板)
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'XDHTH1', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'XDHTH2', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'XYQSRQ', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'XYZZRQ', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'SQDKZE1', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'SQDKZE2', null, null, null, null, 6, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'ZBXXM', null, null, null, null, 7, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'DLXXM', null, null, null, null, 8, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_SZN', 'E_SYNDICATED_LOAN', 'CDXXM', null, null, null, null, 9, null, null, null, null);
commit;




-----------PROJECT_LOAN_BJG_YYYYMMDD(项目贷款模板)。
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'COUN_CODE', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'GROU_MEME', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'BRAN_CODE', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'CUST_SERI', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'LIMI_GROUP', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'LIMI_TYPE', null, null, null, null, 6, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'LIMI_LINE', null, null, null, null, 7, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'PROJ_NAME', null, null, null, null, 8, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'PROJ_TYPE', null, null, null, null, 9, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'SYN_LOAN', null, null, null, null, 10, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'TOTA_INVE_CCY', null, null, null, null, 11, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'TOTA_INVE_AMT', null, null, null, null, 12, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'CAP_CCY', null, null, null, null, 13, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'CAP_CCY_AMT', null, null, null, null, 14, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'PROJ_LOAN_CCY', null, null, null, null, 15, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'PROJ_LOAN_AMT', null, null, null, null, 16, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'PROJ_LOAN_B_DATE', null, null, null, null, 17, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'PROJ_LOAN_E_DATE', null, null, null, null, 18, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'APPR_NO', null, null, null, null, 19, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'PROJ_APPR', null, null, null, null, 20, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'PLAN_LICEN_NO', null, null, null, null, 21, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'CON_LAND_LICEN_NO', null, null, null, null, 22, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'EIA_LICEN_NO', null, null, null, null, 23, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'CON_PER_NO', null, null, null, null, 24, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'OTH_PER_LAND', null, null, null, null, 25, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'OTH_PER_NO', null, null, null, null, 26, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'START_DATE', null, null, null, null, 27, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'COMP_TOTA_INVE_CCY', null, null, null, null, 28, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'COMP_TOTA_INVE_AMT', null, null, null, null, 29, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'COMP_CAP_CCY', null, null, null, null, 30, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('PROJECT_LOAN_BJG', 'E_PROJECT_LOAN', 'COMP_CAP_CCY_AMT', null, null, null, null, 31, null, null, null, null);
commit;

-------------SYN_BJG_YYYYMM(银团贷款模板)
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'XDHTH1', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'XDHTH2', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'XYQSRQ', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'XYZZRQ', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'SQDKZE1', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'SQDKZE2', null, null, null, null, 6, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'ZBXXM', null, null, null, null, 7, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'DLXXM', null, null, null, null, 8, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('SYN_BJG', 'E_SYNDICATED_LOAN', 'CDXXM', null, null, null, null, 9, null, null, null, null);
commit;
