--HSBC
create table E_BRANCH_FIN(
	NBFHZZH                VARCHAR2(60),
	JXBZ                   VARCHAR2(4),
	JXFS                   VARCHAR2(30),
	LL                     NUMBER(10,6),
	ETL_DATE               VARCHAR2(6),
	STATUS                 VARCHAR2(2),
    DATA_FLAG              VARCHAR2(64) 
);

comment on table E_BRANCH_FIN
  is '内部分户账';
comment on column E_BRANCH_FIN.NBFHZZH
  is '内部分户账账户';
comment on column E_BRANCH_FIN.JXBZ
  is '计息标志';
comment on column E_BRANCH_FIN.JXFS
  is '计息方式';
comment on column E_BRANCH_FIN.LL
  is '利率';
comment on column E_BRANCH_FIN.ETL_DATE
  is '上传期数';
comment on column E_BRANCH_FIN.STATUS
  is '数据状态';
comment on column E_BRANCH_FIN.DATA_FLAG
  is '数据标示';
  
--SHH 上海分行财务部 1
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SHH', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SHH', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SHH', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SHH', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_SHH', 'BRANCH_FIN_SHH', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--SZN 深圳分行财务部 2
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SZN', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SZN', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SZN', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SZN', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_SZN', 'BRANCH_FIN_SZN', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--XIA 厦门分行财务部 3
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_XIA', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_XIA', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_XIA', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_XIA', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_XIA', 'BRANCH_FIN_XIA', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--QDO 青岛分行财务部 4
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_QDO', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_QDO', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_QDO', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_QDO', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_QDO', 'BRANCH_FIN_QDO', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--TJN 天津分行财务部 5
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TJN', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TJN', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TJN', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TJN', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_TJN', 'BRANCH_FIN_TJN', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--BJG 北京分行财务部 6
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_BJG', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_BJG', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_BJG', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_BJG', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_BJG', 'BRANCH_FIN_BJG', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--DLN 大连分行财务部 7
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_DLN', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_DLN', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_DLN', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_DLN', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_DLN', 'BRANCH_FIN_DLN', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--WUN 武汉分行财务部 8
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_WUN', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_WUN', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_WUN', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_WUN', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_WUN', 'BRANCH_FIN_WUN', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--GZH 广州分行财务部 9
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_GZH', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_GZH', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_GZH', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_GZH', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_GZH', 'BRANCH_FIN_GZH', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--SUZ 苏州分行财务部 10
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SUZ', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SUZ', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SUZ', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SUZ', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_SUZ', 'BRANCH_FIN_SUZ', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--CQG 重庆分行财务部 11
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CQG', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CQG', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CQG', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CQG', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_CQG', 'BRANCH_FIN_CQG', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--CGU 成都分行财务部 12
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CGU', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CGU', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CGU', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CGU', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_CGU', 'BRANCH_FIN_CGU', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--HAZ 杭州分行财务吧 13
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HAZ', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HAZ', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HAZ', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HAZ', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HAZ', 'BRANCH_FIN_HAZ', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--XAN 西安分行财务部 14
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_XAN', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_XAN', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_XAN', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_XAN', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_XAN', 'BRANCH_FIN_XAN', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--SYA 沈阳分行财务部 15
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SYA', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SYA', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SYA', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_SYA', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_SYA', 'BRANCH_FIN_SYA', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--DNG 东莞分行财务部 16
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_DNG', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_DNG', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_DNG', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_DNG', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_DNG', 'BRANCH_FIN_DNG', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--CNG 长沙分行财务部 17
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CNG', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CNG', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CNG', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CNG', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_CNG', 'BRANCH_FIN_CNG', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--ZHE 郑州分行财务部 18
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_ZHE', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_ZHE', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_ZHE', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_ZHE', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_ZHE', 'BRANCH_FIN_ZHE', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--NGB 宁波分行财务部 19
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NGB', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NGB', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NGB', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NGB', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_NGB', 'BRANCH_FIN_NGB', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--JIN 济南分行财务部 20
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_JIN', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_JIN', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_JIN', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_JIN', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_JIN', 'BRANCH_FIN_JIN', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--TYU 太原分行财务部 21
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TYU', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TYU', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TYU', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TYU', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_TYU', 'BRANCH_FIN_TYU', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--HEF 合肥分行财务部 22
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HEF', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HEF', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HEF', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HEF', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HEF', 'BRANCH_FIN_HEF', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--GZF 佛山分行财务部 23
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_GZF', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_GZF', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_GZF', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_GZF', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_GZF', 'BRANCH_FIN_GZF', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--NJN 南京分行财务部 24
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NJN', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NJN', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NJN', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NJN', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_NJN', 'BRANCH_FIN_NJN', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--KUM 昆明分行财务部 25
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_KUM', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_KUM', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_KUM', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_KUM', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_KUM', 'BRANCH_FIN_KUM', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--WUX 无锡分行财务部 26
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_WUX', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_WUX', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_WUX', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_WUX', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_WUX', 'BRANCH_FIN_WUX', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--HBB 哈尔滨分行财务部 27
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBB', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBB', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBB', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBB', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBB', 'BRANCH_FIN_HBB', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--TGH 唐山分行财务部 28
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TGH', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TGH', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TGH', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_TGH', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_TGH', 'BRANCH_FIN_TGH', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--NNA 南宁分行财务部 29
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NNA', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NNA', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NNA', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NNA', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_NNA', 'BRANCH_FIN_NNA', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--YAZ 扬州分行财务部 30
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_YAZ', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_YAZ', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_YAZ', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_YAZ', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_YAZ', 'BRANCH_FIN_YAZ', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--NTG 南通分行财务部 31
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NTG', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NTG', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NTG', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NTG', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_NTG', 'BRANCH_FIN_NTG', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--CGN 长春分行财务部 32
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CGN', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CGN', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CGN', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_CGN', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_CGN', 'BRANCH_FIN_CGN', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--NCG 南昌分行财务部 33
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NCG', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NCG', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NCG', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_NCG', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_NCG', 'BRANCH_FIN_NCG', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);

--FZU 福州分行财务部 34
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_FZU', 'E_BRANCH_FIN', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_FZU', 'E_BRANCH_FIN', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_FZU', 'E_BRANCH_FIN', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_FZU', 'E_BRANCH_FIN', 'LL', null, null, null, null, 4, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_FZU', 'BRANCH_FIN_FZU', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);


--RRB
create table E_BRANCH_FIN_RRB(
	NBFHZZH                VARCHAR2(60),
	JXBZ                   VARCHAR2(4),
	JXFS                   VARCHAR2(30),
	LL                     NUMBER(10,6),
	BRANCH_TYPE            VARCHAR2(20),
	ETL_DATE               VARCHAR2(6),
	STATUS                 VARCHAR2(2),
    DATA_FLAG              VARCHAR2(64) 
);

comment on table E_BRANCH_FIN_RRB
  is '内部分户账';
comment on column E_BRANCH_FIN_RRB.NBFHZZH
  is '内部分户账账户';
comment on column E_BRANCH_FIN_RRB.JXBZ
  is '计息标志';
comment on column E_BRANCH_FIN_RRB.JXFS
  is '计息方式';
comment on column E_BRANCH_FIN_RRB.LL
  is '利率';
comment on column E_BRANCH_FIN_RRB.BRANCH_TYPE
  is '分行标志';
comment on column E_BRANCH_FIN_RRB.ETL_DATE
  is '上传期数';
comment on column E_BRANCH_FIN_RRB.STATUS
  is '数据状态';
comment on column E_BRANCH_FIN_RRB.DATA_FLAG
  is '数据标示';

insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_RRB', 'E_BRANCH_FIN_RRB', 'BRANCH_TYPE', null, null, null, null, 1, null, null, null, null);  
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_RRB', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_RRB', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_RRB', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_RRB', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_RRB', 'BRANCH_FIN_RRB', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);  
  


------12家村镇行--------------------------------------------------------需要删除
------1.HBBJ
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBBJ', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBBJ', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBBJ', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBBJ', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBBJ', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBBJ', 'BRANCH_FIN_HBBJ', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);
  
------2.HBCB
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCB', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCB', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCB', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCB', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCB', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBCB', 'BRANCH_FIN_HBCB', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);  

------3.HBCD
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCD', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCD', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCD', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCD', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCD', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBCD', 'BRANCH_FIN_HBCD', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);   

------4.HBCF
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCF', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCF', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCF', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCF', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCF', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBCF', 'BRANCH_FIN_HBCF', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null);   

------5.HBCQ
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCQ', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCQ', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCQ', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCQ', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBCQ', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBCQ', 'BRANCH_FIN_HBCQ', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null); 

------6.HBDP
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBDP', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBDP', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBDP', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBDP', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBDP', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBDP', 'BRANCH_FIN_HBDP', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null); 

------7.HBFU
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBFU', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBFU', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBFU', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBFU', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBFU', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBFU', 'BRANCH_FIN_HBFU', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null); 

------8.HBGD
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBGD', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBGD', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBGD', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBGD', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBGD', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBGD', 'BRANCH_FIN_HBGD', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null); 

------9.HBHT
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHT', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHT', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHT', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHT', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHT', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBHT', 'BRANCH_FIN_HBHT', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null); 

------10.HBHU
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHU', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHU', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHU', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHU', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBHU', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBHU', 'BRANCH_FIN_HBHU', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null); 

------11.HBMC
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBMC', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBMC', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBMC', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBMC', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBMC', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBMC', 'BRANCH_FIN_HBMC', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null); 

------12.HBSD
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBSD', 'E_BRANCH_FIN_RRB', 'NBFHZZH', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBSD', 'E_BRANCH_FIN_RRB', 'JXBZ', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBSD', 'E_BRANCH_FIN_RRB', 'JXFS', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBSD', 'E_BRANCH_FIN_RRB', 'LL', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('BRANCH_FIN_HBSD', 'E_BRANCH_FIN_RRB', 'RATE_TYPE', null, null, null, null, 5, null, null, null, null);

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', 'FIN_HBSD', 'BRANCH_FIN_HBSD', 'FIN部门上传文件', null, '4', 'F', 'F', null, null, null); 


---------------------------------------------------------------------需要删除









---------------------------------------------------------------------HSBC
FIN_SHH#MAKER
FIN_SZN#MAKER
FIN_XIA#MAKER
FIN_QDO#MAKER
FIN_TJN#MAKER
FIN_BJG#MAKER
FIN_DLN#MAKER
FIN_WUN#MAKER
FIN_GZH#MAKER
FIN_SUZ#MAKER
FIN_CQG#MAKER
FIN_CGU#MAKER
FIN_HAZ#MAKER
FIN_XAN#MAKER
FIN_SYA#MAKER
FIN_DNG#MAKER
FIN_CNG#MAKER
FIN_ZHE#MAKER
FIN_NGB#MAKER
FIN_JIN#MAKER
FIN_TYU#MAKER
FIN_HEF#MAKER
FIN_GZF#MAKER
FIN_NJN#MAKER
FIN_KUM#MAKER
FIN_WUX#MAKER
FIN_HBB#MAKER
FIN_TGH#MAKER
FIN_NNA#MAKER
FIN_YAZ#MAKER
FIN_NTG#MAKER
FIN_CGN#MAKER
FIN_NCG#MAKER
FIN_FZU#MAKER

FIN_SHH#CHECKER
FIN_SZN#CHECKER
FIN_XIA#CHECKER
FIN_QDO#CHECKER
FIN_TJN#CHECKER
FIN_BJG#CHECKER
FIN_DLN#CHECKER
FIN_WUN#CHECKER
FIN_GZH#CHECKER
FIN_SUZ#CHECKER
FIN_CQG#CHECKER
FIN_CGU#CHECKER
FIN_HAZ#CHECKER
FIN_XAN#CHECKER
FIN_SYA#CHECKER
FIN_DNG#CHECKER
FIN_CNG#CHECKER
FIN_ZHE#CHECKER
FIN_NGB#CHECKER
FIN_JIN#CHECKER
FIN_TYU#CHECKER
FIN_HEF#CHECKER
FIN_GZF#CHECKER
FIN_NJN#CHECKER
FIN_KUM#CHECKER
FIN_WUX#CHECKER
FIN_HBB#CHECKER
FIN_TGH#CHECKER
FIN_NNA#CHECKER
FIN_YAZ#CHECKER
FIN_NTG#CHECKER
FIN_CGN#CHECKER
FIN_NCG#CHECKER
FIN_FZU#CHECKER

---------------------------------------------------------------RRB
FIN_HBBJ#MAKER
FIN_HBCB#MAKER
FIN_HBCD#MAKER
FIN_HBCF#MAKER
FIN_HBCQ#MAKER
FIN_HBDP#MAKER
FIN_HBFU#MAKER
FIN_HBGD#MAKER
FIN_HBHT#MAKER
FIN_HBHU#MAKER
FIN_HBMC#MAKER
FIN_HBSD#MAKER

FIN_HBBJ#CHECKER
FIN_HBCB#CHECKER
FIN_HBCD#CHECKER
FIN_HBCF#CHECKER
FIN_HBCQ#CHECKER
FIN_HBDP#CHECKER
FIN_HBFU#CHECKER
FIN_HBGD#CHECKER
FIN_HBHT#CHECKER
FIN_HBHU#CHECKER
FIN_HBMC#CHECKER
FIN_HBSD#CHECKER