create table CUSTOMER_RISK_RATING_CMB
(
   ETL_DATE               VARCHAR2(6),
   STATUS                 VARCHAR2(2),
   DATA_FLAG              VARCHAR2(64),
   CUSTOMER_NUMBER        VARCHAR2(64),
   CUSTOMER_TYPE          VARCHAR2(100),
   REVIEW_REASON          VARCHAR2(100),
   RISK_RATING            VARCHAR2(64),
   APPROVAL_CANCEL_DATE   VARCHAR2(64),
   REVIEW_STATUS          VARCHAR2(100)
);
comment on table CUSTOMER_RISK_RATING_CMB
  is 'CMB风险等级表';
comment on column CUSTOMER_RISK_RATING_CMB.ETL_DATE
  is '上传月份';
comment on column CUSTOMER_RISK_RATING_CMB.STATUS
  is '数据状态';
comment on column CUSTOMER_RISK_RATING_CMB.DATA_FLAG
  is '数据标示';
comment on column CUSTOMER_RISK_RATING_CMB.CUSTOMER_NUMBER
  is '客户号';
comment on column CUSTOMER_RISK_RATING_CMB.CUSTOMER_TYPE
  is '客户类型';
comment on column CUSTOMER_RISK_RATING_CMB.REVIEW_REASON
  is '审查原因';
comment on column CUSTOMER_RISK_RATING_CMB.RISK_RATING
  is '风险评估';
comment on column CUSTOMER_RISK_RATING_CMB.APPROVAL_CANCEL_DATE
  is '批准取消日期';
comment on column CUSTOMER_RISK_RATING_CMB.REVIEW_STATUS
  is '检查状态';
  

  
create table CUSTOMER_RISK_RATING_GBM
(
   ETL_DATE                   VARCHAR2(6),
   STATUS                     VARCHAR2(2),
   DATA_FLAG                  VARCHAR2(64),
   EXTERNAL_ID                VARCHAR2(48),
   GRID                       VARCHAR2(12),
   RISK_RATING                VARCHAR2(48),
   KYCS_NEXT_RENEWAL_DATE     VARCHAR2(48),
   RESOLVED_COMPLETED_DATE    VARCHAR2(48),
   REQUEST_TYPE               VARCHAR2(200),
   REQUEST_STATUS             VARCHAR2(200),
   PURPOSE_OF_PROFILE_REVIEW  VARCHAR2(200)
);
comment on table CUSTOMER_RISK_RATING_GBM
  is 'GBM风险等级表';


--------------------CUSTOMER_RISK_RATING_CMB
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_CMB', 'CUSTOMER_RISK_RATING_CMB', 'CUSTOMER_NUMBER', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_CMB', 'CUSTOMER_RISK_RATING_CMB', 'CUSTOMER_TYPE', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_CMB', 'CUSTOMER_RISK_RATING_CMB', 'REVIEW_REASON', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_CMB', 'CUSTOMER_RISK_RATING_CMB', 'RISK_RATING', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_CMB', 'CUSTOMER_RISK_RATING_CMB', 'APPROVAL_CANCEL_DATE', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_CMB', 'CUSTOMER_RISK_RATING_CMB', 'REVIEW_STATUS', null, null, null, null, 6, null, null, null, null);
commit;
---------------------CUSTOMER_RISK_RATING_GBM
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_GBM', 'CUSTOMER_RISK_RATING_GBM', 'EXTERNAL_ID', null, null, null, null, 1, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_GBM', 'CUSTOMER_RISK_RATING_GBM', 'GRID', null, null, null, null, 2, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_GBM', 'CUSTOMER_RISK_RATING_GBM', 'RISK_RATING', null, null, null, null, 3, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_GBM', 'CUSTOMER_RISK_RATING_GBM', 'KYCS_NEXT_RENEWAL_DATE', null, null, null, null, 4, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_GBM', 'CUSTOMER_RISK_RATING_GBM', 'RESOLVED_COMPLETED_DATE', null, null, null, null, 5, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_GBM', 'CUSTOMER_RISK_RATING_GBM', 'REQUEST_TYPE', null, null, null, null, 6, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_GBM', 'CUSTOMER_RISK_RATING_GBM', 'REQUEST_STATUS', null, null, null, null, 7, null, null, null, null);
insert into TB_TABLEINFO_300 (FILE_NAME, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COMMENTS, DATA_DIC, ORDNUM, TWO_SEVEN, IS_NOT_NULL, IS_NOT_PK, IS_ONLY)
values ('CUSTOMER_RISK_RATING_GBM', 'CUSTOMER_RISK_RATING_GBM', 'PURPOSE_OF_PROFILE_REVIEW', null, null, null, null, 8, null, null, null, null);
commit;


-----系统配置表
insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', '300_CMB', 'CUSTOMER_RISK_RATING_CMB', 'CMB部门上传文件', null, '4', 'F', 'F', null, null, null);
insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER)
values ('DEPARTMENT', '300_GBM', 'CUSTOMER_RISK_RATING_GBM', 'GBM部门上传文件', null, '4', 'F', 'F', null, null, null);
commit;













