insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('60', '信用卡', null, 2, 1, '0', 22, null, '0', null, null, null, '1', null, null, null, null, null, 'icon-credit-card');
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('6001', '案件处理（高风险）', '/fpages/creditcard/ftl/CreditCardApplyInfo.ftl?level=H', 2, 0, '60', 1, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-default');
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('6002', '案件处理（中风险）', '/fpages/creditcard/ftl/CreditCardApplyInfo.ftl?level=M', 2, 0, '60', 2, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-default');
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('6003', '案件处理（低风险）', '/fpages/creditcard/ftl/CreditCardApplyInfo.ftl?level=L', 2, 0, '60', 3, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-default');
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('6004', '案件处理（Attention List）', '/fpages/creditcard/ftl/CreditCardApplyInfo.ftl?level=A', 2, 0, '60', 4, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-edit');
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('6005', '案件自查手工抽取', '/fpages/creditcard/ftl/CreditCardExtractInfo.ftl', 2, 0, '60', 5, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-default');
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('6006', '案件审核申领', '/fpages/creditcard/ftl/CreditCardApproveApplyInfo.ftl', 2, 0, '60', 6, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-default');
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('6007', '案件审核', '/fpages/creditcard/ftl/CreditCardExtractApproveInfo.ftl', 2, 0, '60', 7, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-default');
insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('6008', '案件分派', '/fpages/creditcard/ftl/CreditCardAssignInfo.ftl', 2, 0, '60', 8, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-default');
